/**
 * Omega derivations: the same decision the mirror makes, printed as the pack's own lines.
 *
 * Why this module exists. The BASIX Track 5 requirement, as transcribed in `docs/ROADMAP.md` §11, is that
 * *"some visible piece of Omega's stateful, auditable-reasoning architecture must be the actual feature,
 * not decoration"*. A transcript written by hand — or generated by a model from a decision it already
 * knows — is decoration: it proves nothing because it could have been written without the engine. So every
 * step here is produced by asking `backend/syncsenta-backend/data/omega_claw_rules.metta` a question and
 * reporting the line that answered it, with its line number. Remove a row from the pack and the trace
 * changes; that is the whole difference between a derivation and a story.
 *
 * Two rules this file follows, stated because both were decisions and neither is obvious from the code:
 *
 * 1. **It is not a second engine.** Normalisation and the decisions themselves come from
 *    `omega-agent/omega-claw-rules.ts` — the module that answers learners today — and
 *    `derive.test.ts` asserts, for every grade, activity, outcome and hint level, that the derivation and
 *    the mirror return the same thing. If they ever disagree, that test fails, which is the same alarm the
 *    drift lock uses for the pack itself.
 * 2. **Absence means different things in different heads.** `(omega-claw-activity …)` rows are a closed
 *    world: the approved list *is* the universe, so "no row binds" is the answer `no`. A value row like
 *    `(= (omega-claw-next-action …) …)` has no catch-all, so "no row binds" means the question cannot be
 *    answered at all, and this throws rather than inventing a default. The failure mode it is guarding
 *    against is the one already recorded in `docs/research/BASIX-FINAL-POSITION.md` §4: a route that
 *    reports success for work it did not do.
 *
 * The pack arrives as text the caller supplied, which is the one thing in this file that makes it usable in
 * a browser: no `node:fs`, no `process.cwd()`, no environment variable, so the same evaluator runs inside a
 * route handler and inside a page on a phone with no network. The reconciler planned in `docs/ROADMAP.md`
 * §11 depends on that, and `derive-browser-safe.test.ts` pins it. A server caller reads the file and passes
 * the text; a client fetches the pack as a static asset. `file` is still required because it is what the
 * transcript cites. When the text holds no statements, this says so with `OmegaClawPackUnavailableError` and
 * the caller prints that it could not derive, which is honest; quietly falling back to a hand-written trace
 * would not be.
 */

import {
  canonicalOmegaClawGrade,
  canonicalOmegaClawToken,
  clampOmegaClawHintLevel,
} from '@/lib/omega-agent/omega-claw-rules';

/**
 * The pack. `text` is the content this module reasons over; `file` is the label every citation prints, so a
 * reviewer can open the pack and check the row. Neither is opened here.
 */
export type PackSource = {
  readonly file: string;
  readonly text: string;
};

/** One statement in the pack, with the line it sits on and the text that was actually read. */
export type PackRow = {
  readonly line: number;
  readonly text: string;
  readonly head: string;
  readonly args: readonly string[];
  /** The right-hand side of an `(= …)` row, or `null` for a bare fact like `(omega-claw-activity …)`. */
  readonly value: string | null;
};

export type DerivationStepKind = 'normalised' | 'question';

export type DerivationStepResult = 'applied' | 'matched' | 'rejected' | 'absent';

export type DerivationStep = {
  readonly index: number;
  readonly kind: DerivationStepKind;
  readonly result: DerivationStepResult;
  /** The expression put to the pack, or for a normalisation step the input it started from. */
  readonly asked: string;
  /** What this step binds: a scope, a hint, `yes`, `no`, or the canonical token. */
  readonly binds: string;
  readonly packLine: number | null;
  readonly packText: string | null;
  /** True when the binding came from a row with variables in it — a catch-all, not a decision by name. */
  readonly isCatchAll: boolean;
};

export type Derivation = {
  /** The head this derivation was built around, e.g. `omega-claw-next-action`. */
  readonly question: string;
  readonly packFile: string;
  readonly packRowCount: number;
  readonly steps: readonly DerivationStep[];
  readonly conclusion: string;
  readonly conclusionLine: number | null;
};

export class OmegaClawPackUnavailableError extends Error {
  constructor(file: string, reason: string) {
    super(`Omega rule pack is unavailable (${file}): ${reason}`);
    this.name = 'OmegaClawPackUnavailableError';
  }
}

/** A value question the pack cannot answer. Distinct from "the pack answers no". */
export class OmegaClawNoRowError extends Error {
  constructor(asked: string) {
    super(`no Omega rule row binds ${asked} — the pack cannot answer this question`);
    this.name = 'OmegaClawNoRowError';
  }
}

/** A question the pack refuses because the work was never approved for this learner. */
export class OmegaClawNotApprovedError extends Error {
  constructor(asked: string) {
    super(`not approved by the pack: no row for ${asked}`);
    this.name = 'OmegaClawNotApprovedError';
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Parsing
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Read the pack's statements, keeping line numbers and raw text.
 *
 * Deliberately a line-shaped parser, not a general MeTTa interpreter: the pack this project ships is one
 * statement per line, which is also what makes `file:line` citations possible. A multi-line form would be
 * silently skipped here, and `derive.test.ts` pins the line numbers of the rows it cites so a skipped form
 * shows up as a wrong number rather than as a confident wrong answer.
 */
export function parsePack(source: string): PackRow[] {
  const rows: PackRow[] = [];
  const lines = source.split('\n');

  for (let i = 0; i < lines.length; i += 1) {
    const raw = lines[i];
    const text = raw.replace(/;;.*$/, '').trim();
    if (!text) continue;

    // (= (omega-claw-scope-for grade6) introductory)
    const equality = text.match(/^\(\s*=\s*\(\s*([\w-]+)((?:\s+[^()]+)?)\s*\)\s+(\S+)\s*\)$/);
    if (equality) {
      const [, head, argsRaw, value] = equality;
      rows.push({
        line: i + 1,
        text,
        head,
        args: argsRaw.trim().split(/\s+/).filter(Boolean),
        value,
      });
      continue;
    }

    // (omega-claw-activity grade6 ai-input-output)
    const relation = text.match(/^\(\s*([\w-]+)((?:\s+[^()]+)?)\s*\)$/);
    if (relation) {
      const [, head, argsRaw] = relation;
      rows.push({
        line: i + 1,
        text,
        head,
        args: argsRaw.trim().split(/\s+/).filter(Boolean),
        value: null,
      });
    }
  }

  return rows;
}

function loadRows(source: PackSource): { readonly file: string; readonly rows: PackRow[] } {
  // Guarded rather than left to a `undefined.split` crash: this fires when a caller forgets the source,
  // and the message a teacher's console should show is "nobody handed me a pack", not a TypeError.
  if (typeof source?.text !== 'string') {
    throw new OmegaClawPackUnavailableError(
      source?.file ?? '<no source supplied>',
      'the caller did not supply pack text',
    );
  }

  const rows = parsePack(source.text);
  if (rows.length === 0) {
    throw new OmegaClawPackUnavailableError(source.file, 'the pack contains no statements');
  }
  return { file: source.file, rows };
}

// ─────────────────────────────────────────────────────────────────────────────
// Asking the pack
// ─────────────────────────────────────────────────────────────────────────────

type Draft = Omit<DerivationStep, 'index'>;

type Trace = {
  readonly file: string;
  readonly packRowCount: number;
  readonly rows: readonly PackRow[];
  readonly drafts: Draft[];
};

function traceFrom(source: PackSource): Trace {
  const { file, rows } = loadRows(source);
  return { file, packRowCount: rows.length, drafts: [], rows };
}

function normalise(trace: Trace, label: string, input: string, binds: string): void {
  if (input === binds) return;
  trace.drafts.push({
    kind: 'normalised',
    result: 'applied',
    asked: `${label} input "${input}"`,
    binds,
    packLine: null,
    packText: null,
    isCatchAll: false,
  });
}

function askedExpression(head: string, args: readonly string[]): string {
  return `(${head} ${args.join(' ')})`;
}

function isCatchAll(row: PackRow): boolean {
  return row.args.some((arg) => arg.startsWith('$'));
}

/**
 * Bind `args` to the pack's rows for `head`, first-match with concrete rows ahead of catch-alls — the
 * precedence the Rust façade applies in `scope_for()` (try `introductory`, then `senior-deep`, then the
 * default) and the reason a Grade 6 learner is never told they are out of scope.
 *
 * Every concrete row examined before the winner is recorded, so the trace shows what the engine rejected
 * on the way to its answer. That is the part a hand-written explanation never contains, and it is the half
 * a teacher actually wants when they disagree.
 */
function ask(
  trace: Trace,
  head: string,
  args: readonly string[],
): { readonly binds: string; readonly line: number | null } {
  const candidates = trace.rows.filter(
    (row) => row.head === head && row.args.length === args.length,
  );
  if (candidates.length === 0) {
    throw new OmegaClawPackUnavailableError(trace.file, `the pack has no ${head} rows to ask`);
  }
  const expression = askedExpression(head, args);

  const ordered = [
    ...candidates.filter((row) => !isCatchAll(row)),
    ...candidates.filter(isCatchAll),
  ];

  for (const row of ordered) {
    const binds = bindRow(row, args);
    if (binds === null) {
      if (!isCatchAll(row)) {
        trace.drafts.push({
          kind: 'question',
          result: 'rejected',
          asked: expression,
          binds: 'no match',
          packLine: row.line,
          packText: row.text,
          isCatchAll: false,
        });
      }
      continue;
    }

    trace.drafts.push({
      kind: 'question',
      result: 'matched',
      asked: expression,
      binds,
      packLine: row.line,
      packText: row.text,
      isCatchAll: isCatchAll(row),
    });
    return { binds, line: row.line };
  }

  // Nothing bound. A fact head is a closed world, so absence answers no; a value head cannot answer.
  const isFact = candidates.every((row) => row.value === null);
  if (isFact) {
    trace.drafts.push({
      kind: 'question',
      result: 'absent',
      asked: expression,
      binds: 'no',
      packLine: null,
      packText: null,
      isCatchAll: false,
    });
    return { binds: 'no', line: null };
  }
  throw new OmegaClawNoRowError(expression);
}

/** Unify `args` against one row. Returns the binding, or null when the row does not match. */
function bindRow(row: PackRow, args: readonly string[]): string | null {
  for (let i = 0; i < row.args.length; i += 1) {
    const symbol = row.args[i];
    if (symbol.startsWith('$')) continue;
    if (symbol !== args[i]) return null;
  }
  if (row.value !== null) {
    // A value row may still bind variables on the left (the transfer catch-all); the answer is its right side.
    return row.value;
  }
  return 'yes';
}

function finish(trace: Trace, question: string, answer: { binds: string; line: number | null }): Derivation {
  return {
    question,
    packFile: trace.file,
    packRowCount: trace.packRowCount,
    steps: trace.drafts.map((draft, i) => ({ ...draft, index: i + 1 })),
    conclusion: answer.binds,
    conclusionLine: answer.line,
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// The four questions the product asks
// ─────────────────────────────────────────────────────────────────────────────

/** `(omega-claw-scope-for <grade>)` — is this learner in the programme, and on which tier. */
export function deriveScope(grade: string, source: PackSource): Derivation {
  const trace = traceFrom(source);
  const canonical = canonicalOmegaClawGrade(grade);
  normalise(trace, 'grade', grade, canonical);
  const answer = ask(trace, 'omega-claw-scope-for', [canonical]);
  return finish(trace, 'omega-claw-scope-for', answer);
}

/** `(omega-claw-hint <level>)` — which rung of the ladder fires, after the clamp the mirror owns. */
export function deriveHintLevel(level: number, source: PackSource): Derivation {
  const trace = traceFrom(source);
  const clamped = clampOmegaClawHintLevel(level);
  normalise(trace, 'hint level', String(level), String(clamped));
  const answer = ask(trace, 'omega-claw-hint', [String(clamped)]);
  return finish(trace, 'omega-claw-hint', answer);
}

/** `(omega-claw-activity <grade> <activity>)`, asked only after the scope row allows the grade at all. */
export function deriveActivityApproval(
  input: { readonly grade: string; readonly activity: string },
  source: PackSource,
): Derivation {
  const trace = traceFrom(source);
  const grade = canonicalOmegaClawGrade(input.grade);
  normalise(trace, 'grade', input.grade, grade);
  const activity = canonicalOmegaClawToken(input.activity);
  normalise(trace, 'activity', input.activity, activity);

  const scope = ask(trace, 'omega-claw-scope-for', [grade]);
  if (scope.binds === 'blocked') {
    return finish(trace, 'omega-claw-activity', { binds: 'no', line: scope.line });
  }
  const approval = ask(trace, 'omega-claw-activity', [grade, activity]);
  return finish(trace, 'omega-claw-activity', approval);
}

/**
 * The decision a learner actually receives: scope, approval, then the outcome row.
 *
 * Ordered that way because that is the order the pack means: an unapproved activity has no next action, and
 * saying so by throwing is what keeps this from becoming the route that returns a confident answer about
 * work the pack never sanctioned.
 */
export function deriveNextAction(
  input: {
    readonly grade: string;
    readonly activity: string;
    readonly outcome: string;
  },
  source: PackSource,
): Derivation {
  const trace = traceFrom(source);
  const grade = canonicalOmegaClawGrade(input.grade);
  normalise(trace, 'grade', input.grade, grade);
  const activity = canonicalOmegaClawToken(input.activity);
  normalise(trace, 'activity', input.activity, activity);

  ask(trace, 'omega-claw-scope-for', [grade]);
  const approval = ask(trace, 'omega-claw-activity', [grade, activity]);
  if (approval.binds !== 'yes') {
    throw new OmegaClawNotApprovedError(askedExpression('omega-claw-activity', [grade, activity]));
  }
  const outcome = canonicalOmegaClawToken(input.outcome);
  normalise(trace, 'outcome', input.outcome, outcome);
  const answer = ask(trace, 'omega-claw-next-action', [outcome]);
  return finish(trace, 'omega-claw-next-action', answer);
}

/** `(omega-claw-can-unlock-transfer <correct> <explained>)` — the pedagogy's one hard gate. */
export function deriveTransfer(
  input: { readonly correct: boolean; readonly explained: boolean },
  source: PackSource,
): Derivation {
  const trace = traceFrom(source);
  const args = [String(input.correct), String(input.explained)];
  const answer = ask(trace, 'omega-claw-can-unlock-transfer', args);
  return finish(trace, 'omega-claw-can-unlock-transfer', answer);
}

// ─────────────────────────────────────────────────────────────────────────────
// Printing
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Render a derivation for the teacher's glass box.
 *
 * Consecutive refusals of the same question collapse to one line: thirteen rejected activity rows are
 * evidence, and thirteen bullets are noise. The count stays visible, so nothing is hidden by the grouping.
 *
 * This prints MeTTa symbols, never the learner-facing sentences: wording lives in `OMEGA_CLAW_HINT_COPY`
 * and `OMEGA_CLAW_ACTION_COPY` and a third home for it is how two copies start disagreeing.
 */
/**
 * The last segment of the pack label, without `node:path`. Every citation in a transcript is short-form for
 * the same reason the Rust façade prints a rule name rather than a working directory: the reader has to be
 * able to line the number up against the file they have open.
 */
function lastPathSegment(path: string): string {
  return path.split(/[\\/]/).pop() ?? path;
}

export function renderDerivation(derivation: Derivation): string {
  const file = lastPathSegment(derivation.packFile);
  const steps = derivation.steps;
  const out: string[] = [
    `Omega derivation · ${derivation.question} · ${file} (${derivation.packRowCount} statements)`,
  ];

  let cursor = 0;
  while (cursor < steps.length) {
    const step = steps[cursor];

    if (step.kind === 'question' && step.result === 'rejected') {
      let end = cursor;
      while (end < steps.length && steps[end].kind === 'question' && steps[end].result === 'rejected') {
        end += 1;
      }
      const tried = end - cursor;
      out.push(
        tried === 1
          ? `${step.index}. ${step.asked} — no match at ${file}:${step.packLine}`
          : `${step.index}. ${step.asked} — ${tried} rows tried, no match`,
      );
      cursor = end;
      continue;
    }

    if (step.kind === 'normalised') {
      out.push(`${step.index}. ${step.asked} → ${step.binds}`);
    } else if (step.result === 'absent') {
      out.push(`${step.index}. ${step.asked} — no row binds, so the answer is ${step.binds}`);
    } else {
      const catchAll = step.isCatchAll ? ' (catch-all row)' : '';
      out.push(`${step.index}. ${step.asked} → ${step.binds}${catchAll} — ${file}:${step.packLine}`);
    }
    cursor += 1;
  }

  const tail =
    derivation.conclusionLine === null
      ? `∴ ${derivation.conclusion}`
      : `∴ ${derivation.conclusion} — ${file}:${derivation.conclusionLine}`;
  out.push(tail);
  return out.join('\n');
}
