// Build one authoritative baseline migration from the live schema export.
//
// Reads the section blocks captured from the running Supabase project and emits
// them in dependency order, so a scratch database can be brought to exactly the
// shape production is in. This exists because neither migration directory in the
// repo describes production: `supabase/migrations/` and
// `backend/syncsenta-backend/migrations/` together define 93 tables, only 20 of
// which are live, while 6 live tables have no readable DDL anywhere in the repo.
//
//   node build_baseline.js > ../migrations_live/20260928000000_live_baseline.sql
//
// Reorder note: triggers and RLS policies both call database functions, so
// functions are emitted before them even though they arrive in a later block.
const fs = require('fs');
const path = require('path');

const SRC = __dirname;
const ORDER = [
  ['01_objects.sql', 'extensions'],
  ['01_objects.sql', 'enums'],
  ['01_objects.sql', 'sequences'],
  ['01_objects.sql', 'tables'],
  ['02_constraints.sql', 'constraints'],
  ['02_constraints.sql', 'indexes'],
  ['04_functions_views.sql', 'functions'],
  ['02_constraints.sql', 'triggers'],
  ['03_rls_grants.sql', 'rls'],
  ['04_functions_views.sql', 'views'],
  ['03_rls_grants.sql', 'grants'],
];

function sections(file) {
  const text = fs.readFileSync(path.join(SRC, file), 'utf8');
  const out = {};
  let current = null;
  for (const line of text.split('\n')) {
    const m = line.match(/^-- SECTION: ([a-z ]+)\s*$/);
    if (m) {
      current = m[1];
      out[current] = [];
      continue;
    }
    if (current) out[current].push(line);
  }
  return Object.fromEntries(
    Object.entries(out).map(([k, v]) => [k, v.join('\n').trim()]),
  );
}

const cache = {};
const get = (file, name) => {
  if (!cache[file]) cache[file] = sections(file);
  return cache[file][name];
};

const parts = [
  `-- Live schema baseline, captured ${new Date().toISOString().slice(0, 10)} from the
-- SyncSenta production project (ref tumikgwhrbvirpjswlzh, PostgreSQL 17.6).
--
-- Generated by supabase/live_schema_export/build_baseline.js from the blocks in
-- this directory; do not hand-edit. See db/README.md for why this, and not
-- supabase/migrations/, is the description of what is really running.
--
-- 26 tables, all row level security enabled. Nothing here is inferred.`,
];

for (const [file, name] of ORDER) {
  const body = get(file, name);
  if (!body || body === '-- none' || body === '-- none\n') continue;
  parts.push(`\n-- ==== ${name} (${file}) ====\n${body}`);
}

process.stdout.write(parts.join('\n') + '\n');
