/**
 * MeTTa-Driven Student Interface
 * 
 * 99.99% agent-controlled UI that renders based on MeTTa reasoning.
 * All interactions, animations, and content are generated by MeTTa programs.
 */

'use client';

import { useEffect, useState, useCallback } from 'react';
import { mettaEducationSystem, MeTTaSession } from '@/lib/omega-agent/metta-core';
import { useAuth } from '@/hooks/use-auth';

interface MeTTaUIElement {
  type: 'button' | 'text' | 'image' | 'animation' | 'input' | 'progress' | 'celebration';
  id: string;
  content: any;
  position: { x: number; y: number };
  size: { width: number; height: number };
  behavior: string[];
  culturalContext: string[];
  mettaProgram: string;
}

interface MeTTaGameState {
  currentActivity: string;
  progress: number;
  competencyLevels: Record<string, number>;
  culturalElements: string[];
  animations: string[];
  feedback: string[];
  nextActions: string[];
}

export default function MeTTaStudentInterface() {
  const { user } = useAuth();
  const [mettaSession, setMettaSession] = useState<MeTTaSession | null>(null);
  const [gameState, setGameState] = useState<MeTTaGameState>({
    currentActivity: 'loading',
    progress: 0,
    competencyLevels: {},
    culturalElements: [],
    animations: [],
    feedback: [],
    nextActions: []
  });
  const [uiElements, setUIElements] = useState<MeTTaUIElement[]>([]);
  const [isThinking, setIsThinking] = useState(false);

  // Initialize MeTTa session
  useEffect(() => {
    if (user?.id) {
      const session = mettaEducationSystem.createSession(user.id, 'grade2');
      setMettaSession(session);
      
      // Start with initial MeTTa query to determine UI
      initializeInterface(session);
    }
  }, [user?.id]);

  const initializeInterface = async (session: MeTTaSession) => {
    setIsThinking(true);

    try {
      // Restore any previously persisted session facts from Supabase
      await session.restore();

      // Query MeTTa for initial UI setup
      const initQuery = '(initialize-student-interface grade2 kenya)';
      const response = await session.processInteraction({
        type: 'interface_init',
        query: initQuery,
        userId: session.userId
      });

      // Generate UI based on MeTTa response
      const elements = await generateUIFromMeTTa(response);
      setUIElements(elements);

      // Set initial game state
      await updateGameState(session);

    } catch (error) {
      console.error('MeTTa interface initialization failed:', error);
    } finally {
      setIsThinking(false);
    }
  };

  const generateUIFromMeTTa = async (mettaResponse: any): Promise<MeTTaUIElement[]> => {
    // This function converts MeTTa reasoning output into React UI elements
    const elements: MeTTaUIElement[] = [];

    // MeTTa program for Grade 2 number garden
    elements.push({
      type: 'text',
      id: 'welcome-message',
      content: {
        text: 'Karibu! Welcome to your learning garden! 🌻',
        style: { fontSize: '24px', color: '#16A34A', fontWeight: 'bold' }
      },
      position: { x: 50, y: 20 },
      size: { width: 400, height: 60 },
      behavior: ['fade-in', 'gentle-bounce'],
      culturalContext: ['kiswahili-greeting', 'kenyan-flowers'],
      mettaProgram: '(welcome-message grade2 (cultural-context kenya kiswahili))'
    });

    // MeTTa-generated activity selector
    elements.push({
      type: 'button',
      id: 'activity-matatu-counting',
      content: {
        text: '🚐 Count Matatu Passengers',
        description: 'Help count passengers at the matatu stage in Nairobi',
        culturalNote: 'Matatus are popular public transport in Kenya'
      },
      position: { x: 50, y: 120 },
      size: { width: 300, height: 80 },
      behavior: ['hover-grow', 'cultural-animation'],
      culturalContext: ['nairobi-matatus', 'public-transport', 'counting-1-14'],
      mettaProgram: `(activity-button matatu-counting 
                      (cultural-context kenyan-transport)
                      (competency counting numbers-1-14)
                      (difficulty easy))`
    });

    elements.push({
      type: 'button',
      id: 'activity-safari-shapes',
      content: {
        text: '🦁 Safari Shape Hunt',
        description: 'Find shapes in Maasai Mara animals',
        culturalNote: 'Learn shapes using Kenyan wildlife'
      },
      position: { x: 380, y: 120 },
      size: { width: 300, height: 80 },
      behavior: ['hover-grow', 'animal-sounds'],
      culturalContext: ['maasai-mara', 'safari-animals', 'geometric-shapes'],
      mettaProgram: `(activity-button safari-shapes
                      (cultural-context kenyan-wildlife)
                      (competency shapes recognition)
                      (difficulty medium))`
    });

    elements.push({
      type: 'button',
      id: 'activity-shilling-math',
      content: {
        text: '💰 Shilling Shop',
        description: 'Practice addition with Kenyan shillings',
        culturalNote: 'Learn money using Kenya shillings'
      },
      position: { x: 50, y: 220 },
      size: { width: 300, height: 80 },
      behavior: ['hover-grow', 'coin-jingle'],
      culturalContext: ['kenyan-currency', 'market-shopping', 'basic-addition'],
      mettaProgram: `(activity-button shilling-math
                      (cultural-context kenyan-economy)
                      (competency addition money-recognition)
                      (difficulty medium))`
    });

    // MeTTa-driven progress indicator
    elements.push({
      type: 'progress',
      id: 'competency-progress',
      content: {
        subjects: {
          mathematics: { level: 2.3, activities: 5, culturalMastery: 0.8 },
          kiswahili: { level: 1.9, activities: 3, culturalMastery: 0.9 },
          english: { level: 2.1, activities: 4, culturalMastery: 0.7 }
        }
      },
      position: { x: 380, y: 220 },
      size: { width: 300, height: 150 },
      behavior: ['smooth-transitions', 'celebration-on-progress'],
      culturalContext: ['cbc-curriculum', 'grade2-expectations'],
      mettaProgram: `(progress-display 
                      (competencies mathematics kiswahili english)
                      (cultural-adaptation kenyan-examples)
                      (grade-level 2))`
    });

    return elements;
  };

  const updateGameState = async (session: MeTTaSession) => {
    const stateQuery = '(get-current-state $userId mathematics grade2)';
    const response = await session.processInteraction({
      type: 'state_query',
      query: stateQuery,
      userId: session.userId
    });

    setGameState(prev => ({
      ...prev,
      currentActivity: response.data?.activity || 'number-garden',
      progress: response.data?.progress || 0,
      competencyLevels: response.data?.competencies || {},
      culturalElements: response.data?.culturalElements || ['kenyan-context'],
      feedback: response.data?.feedback || []
    }));
  };

  const handleMeTTaInteraction = useCallback(async (elementId: string, interactionType: string, data?: any) => {
    if (!mettaSession) return;

    setIsThinking(true);

    try {
      const interaction = {
        type: 'ui_interaction',
        elementId,
        interactionType,
        data,
        timestamp: Date.now()
      };

      // Use remote endpoint so the interaction is persisted server-side
      const response = await mettaSession.processInteractionRemote(interaction as Record<string, unknown>);
      const resp = response as any;

      // Persist current session facts after every interaction
      await mettaSession.persist(
        gameState.competencyLevels,
        { type: interaction.type, input: interaction as any, result: response }
      );

      // Update UI based on MeTTa response
      if (resp?.data?.newElements) {
        const newElements = await generateUIFromMeTTa(resp);
        setUIElements(prev => [...prev, ...newElements]);
      }

      if (resp?.data?.updateGameState) {
        await updateGameState(mettaSession);
      }

      if (resp?.data?.celebrations) {
        showMeTTaCelebration(resp.data.celebrations);
      }

    } catch (error) {
      console.error('MeTTa interaction failed:', error);
    } finally {
      setIsThinking(false);
    }
  }, [mettaSession, gameState.competencyLevels]);

  const showMeTTaCelebration = (celebrations: string[]) => {
    // MeTTa-driven celebration animations
    celebrations.forEach(celebration => {
      const celebrationElement: MeTTaUIElement = {
        type: 'celebration',
        id: `celebration-${Date.now()}`,
        content: { 
          type: celebration,
          culturalElements: ['safari-animals', 'kenyan-flag', 'celebration-dance']
        },
        position: { x: 300, y: 200 },
        size: { width: 200, height: 200 },
        behavior: ['burst-animation', 'cultural-music', 'auto-remove-5s'],
        culturalContext: ['kenyan-celebrations', 'achievement-recognition'],
        mettaProgram: `(celebration ${celebration} (cultural-context kenya))`
      };
      
      setUIElements(prev => [...prev, celebrationElement]);
      
      // Remove after animation
      setTimeout(() => {
        setUIElements(prev => prev.filter(el => el.id !== celebrationElement.id));
      }, 5000);
    });
  };

  const renderMeTTaElement = (element: MeTTaUIElement) => {
    const style = {
      position: 'absolute' as const,
      left: element.position.x,
      top: element.position.y,
      width: element.size.width,
      height: element.size.height,
      transition: 'all 0.3s ease'
    };

    switch (element.type) {
      case 'text':
        return (
          <div key={element.id} style={style}>
            <div
              style={element.content.style}
              className="text-center animate-pulse"
            >
              {element.content.text}
            </div>
            {element.culturalContext.length > 0 && (
              <div className="text-xs text-gray-500 mt-1">
                🌍 Cultural Context: {element.culturalContext.join(', ')}
              </div>
            )}
          </div>
        );

      case 'button':
        return (
          <div key={element.id} style={style}>
            <button
              onClick={() => handleMeTTaInteraction(element.id, 'click')}
              className="w-full h-full bg-gradient-to-r from-green-400 to-emerald-500 hover:from-green-500 hover:to-emerald-600 
                         text-white font-bold rounded-xl shadow-lg hover:shadow-xl transform hover:scale-105 
                         transition-all duration-200 flex flex-col items-center justify-center p-3"
              disabled={isThinking}
            >
              <div className="text-lg mb-1">{element.content.text}</div>
              <div className="text-xs opacity-90">{element.content.description}</div>
              <div className="text-xs mt-1 bg-white/20 rounded px-2 py-1">
                {element.content.culturalNote}
              </div>
            </button>
            <div className="mt-2 text-xs text-purple-600">
              🧠 MeTTa: {element.mettaProgram.slice(0, 50)}...
            </div>
          </div>
        );

      case 'progress':
        return (
          <div key={element.id} style={style}>
            <div className="bg-white rounded-xl shadow-lg p-4">
              <h3 className="text-lg font-bold text-center mb-3">Your Learning Progress</h3>
              {Object.entries(element.content.subjects).map(([subject, data]: [string, any]) => (
                <div key={subject} className="mb-3">
                  <div className="flex justify-between items-center mb-1">
                    <span className="text-sm font-medium capitalize">{subject}</span>
                    <span className="text-sm text-gray-600">{data.level.toFixed(1)}/5.0</span>
                  </div>
                  <div className="w-full bg-gray-200 rounded-full h-3">
                    <div 
                      className="bg-gradient-to-r from-blue-500 to-purple-500 h-3 rounded-full transition-all duration-1000"
                      style={{ width: `${(data.level / 5) * 100}%` }}
                    ></div>
                  </div>
                  <div className="text-xs text-gray-500 mt-1">
                    Cultural Mastery: {(data.culturalMastery * 100).toFixed(0)}% • {data.activities} activities
                  </div>
                </div>
              ))}
            </div>
          </div>
        );

      case 'celebration':
        return (
          <div key={element.id} style={style}>
            <div className="flex items-center justify-center h-full">
              <div className="text-6xl animate-bounce">
                {element.content.type === 'achievement' ? '🏆' : 
                 element.content.type === 'progress' ? '🌟' : '🎉'}
              </div>
              <div className="text-4xl ml-4 animate-pulse">
                {element.content.culturalElements.includes('safari-animals') ? '🦁🐘🦓' :
                 element.content.culturalElements.includes('kenyan-flag') ? '🇰🇪' : '✨'}
              </div>
            </div>
            <div className="text-center text-sm mt-2 text-purple-600">
              🧠 MeTTa Celebration: {element.mettaProgram}
            </div>
          </div>
        );

      default:
        return (
          <div key={element.id} style={style} className="bg-gray-100 border-2 border-dashed border-gray-300 rounded p-2">
            <div className="text-xs text-gray-600">MeTTa Element: {element.type}</div>
          </div>
        );
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-sky-100 via-green-50 to-yellow-50 relative overflow-hidden">
      {/* MeTTa System Status */}
      <div className="absolute top-4 right-4 z-50">
        <div className="bg-white/90 backdrop-blur-sm rounded-lg p-3 shadow-lg">
          <div className="flex items-center gap-2 mb-2">
            <div className={`w-3 h-3 rounded-full ${mettaSession ? 'bg-green-500' : 'bg-red-500'}`}></div>
            <span className="text-sm font-medium">MeTTa System</span>
          </div>
          <div className="text-xs text-gray-600">
            Session: {mettaSession?.userId.slice(0, 8)}...<br/>
            Grade: {mettaSession?.grade || 'Loading'}<br/>
            Elements: {uiElements.length}
          </div>
          {isThinking && (
            <div className="text-xs text-purple-600 mt-2 animate-pulse">
              🧠 MeTTa reasoning...
            </div>
          )}
        </div>
      </div>

      {/* Cultural Background Elements */}
      <div className="absolute inset-0 opacity-10">
        <div className="text-9xl absolute top-10 left-10">🗻</div> {/* Mount Kenya */}
        <div className="text-6xl absolute top-32 right-20">🦒</div> {/* Giraffe */}
        <div className="text-8xl absolute bottom-20 left-20">🌍</div> {/* Africa */}
        <div className="text-7xl absolute bottom-10 right-10">🌺</div> {/* Flowers */}
      </div>

      {/* MeTTa-Generated UI Elements */}
      <div className="relative z-10">
        {uiElements.map(renderMeTTaElement)}
      </div>

      {/* MeTTa Debug Panel (Development Only) */}
      {process.env.NODE_ENV === 'development' && (
        <div className="fixed bottom-4 left-4 bg-black/80 text-white p-4 rounded-lg text-xs max-w-md max-h-60 overflow-y-auto">
          <div className="font-bold mb-2">MeTTa Debug Panel</div>
          <div>Active Session: {mettaSession?.userId}</div>
          <div>UI Elements: {uiElements.length}</div>
          <div>Current Activity: {gameState.currentActivity}</div>
          <div>Competency Levels:</div>
          {Object.entries(gameState.competencyLevels).map(([subject, level]) => (
            <div key={subject} className="ml-2">
              {subject}: {level}/5.0
            </div>
          ))}
          <div className="mt-2">
            <div className="font-bold">Session State (MeTTa):</div>
            {mettaSession?.getSessionState().slice(0, 3).map((state, idx) => (
              <div key={idx} className="ml-2 truncate">
                {state}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Loading State */}
      {!mettaSession && (
        <div className="absolute inset-0 flex items-center justify-center bg-white/80 backdrop-blur-sm">
          <div className="text-center">
            <div className="text-6xl animate-spin mb-4">🧠</div>
            <div className="text-2xl font-bold text-purple-600">Initializing MeTTa System</div>
            <div className="text-gray-600 mt-2">Setting up neuro-symbolic AI for Grade 2 learning...</div>
          </div>
        </div>
      )}
    </div>
  );
}