/**
 * Builds the scheme-of-work print window with DOM calls only.
 *
 * Why this file exists: `components/generate-scheme-of-work-dialog.tsx` used to
 * produce the whole document as one interpolated template string and hand it to
 * `windowWin.document.write(...)`. `window.open('')` returns an `about:blank`
 * window that inherits the opener's origin and session, so the teacher's own
 * Sub-Strand field was an HTML-parsing sink: `<img src=x onerror=…>` executed
 * with the teacher's Supabase token, as did anything the model wrote into the
 * scheme body. CodeQL does not model `document.write` on a child window as a
 * sink, so a green security scan was not evidence either way.
 *
 * The rule this module holds to: every caller-supplied value enters the
 * document as a *text node*, and the generated scheme table is copied with
 * `importNode`, never read back as `.innerHTML`. That makes the safe path the
 * only path — there is no string here that a caller can lengthen into markup.
 *
 * Types are the real DOM (`Document`, `Node`), not a structural look-alike: a
 * stub cannot name `Document`'s methods without also pretending to be `Node`,
 * and `tsc` refuses to let such a stub flow into `replaceChildren`/`appendChild`
 * signatures. So this is ordinary DOM code and the tests pass a small fake
 * through one explicit cast per call — which keeps the compiler checking real
 * signatures and keeps the suite jsdom-free on a 3.7 GB laptop.
 */

export interface SchemePrintMeta {
  grade: string;
  subject: string;
  strand: string;
  subStrand: string;
  lessonsPerWeek: number;
}

const PRINT_STYLES = `
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap');
  body { font-family: 'Inter', sans-serif; padding: 40px; color: #1a1a1a; line-height: 1.5; }
  table { width: 100%; border-collapse: collapse; margin-top: 20px; table-layout: fixed; border: 2px solid #000; }
  th, td { border: 1px solid #000; padding: 12px; text-align: left; vertical-align: top; font-size: 11px; word-wrap: break-word; }
  th { background-color: #f3f4f6; font-weight: bold; text-transform: uppercase; border-bottom: 2px solid #000; }
  h1 { color: #256E82; font-size: 24px; margin-bottom: 10px; border-bottom: 2px solid #256E82; padding-bottom: 5px; }
  .meta { margin-bottom: 25px; display: grid; grid-template-columns: 1fr 1fr; gap: 20px; font-size: 14px; background: #f9fafb; padding: 15px; border-radius: 8px; }
  .meta p { margin: 4px 0; }
  .footer { margin-top: 40px; font-size: 10px; color: #666; text-align: center; border-top: 1px solid #eee; padding-top: 10px; }
  @media print {
    body { padding: 0; }
    @page { size: landscape; margin: 1cm; }
  }
`;

/** `<p><strong>Label:</strong> value</p>`, with the value as a text node. */
function metaRow(
  doc: Document,
  label: string,
  value: string | number,
): HTMLElement {
  const paragraph = doc.createElement('p');
  const strong = doc.createElement('strong');
  strong.textContent = `${label}:`;
  paragraph.appendChild(strong);
  paragraph.appendChild(doc.createTextNode(` ${String(value)}`));
  return paragraph;
}

function block(doc: Document, tagName: string, className: string): HTMLElement {
  const element = doc.createElement(tagName);
  element.setAttribute('class', className);
  return element;
}

/**
 * Fill `doc` — the print window's document — with the scheme.
 *
 * @param body the already-rendered scheme subtree in the opener document,
 *   usually `document.getElementById('scheme-print-area')`. It is cloned with
 *   `importNode` and appended once; its markup is never serialised and reparsed.
 */
export function buildSchemePrintDocument(
  doc: Document,
  meta: SchemePrintMeta,
  body: Node,
): void {
  doc.title = `SyncSenta - Scheme of Work: ${meta.subStrand}`;

  const styles = doc.createElement('style');
  styles.textContent = PRINT_STYLES;
  doc.head.appendChild(styles);

  const heading = doc.createElement('h1');
  heading.textContent = 'SyncSenta: CBC Scheme of Work';
  doc.body.appendChild(heading);

  const metaBlock = block(doc, 'div', 'meta');
  const left = block(doc, 'div', 'meta-column');
  left.appendChild(metaRow(doc, 'Grade', meta.grade));
  left.appendChild(metaRow(doc, 'Subject', meta.subject));
  left.appendChild(metaRow(doc, 'Term', '[To be filled]'));
  const right = block(doc, 'div', 'meta-column');
  right.appendChild(metaRow(doc, 'Strand', meta.strand));
  right.appendChild(metaRow(doc, 'Sub-Strand', meta.subStrand));
  right.appendChild(metaRow(doc, 'Lessons', meta.lessonsPerWeek));
  metaBlock.appendChild(left);
  metaBlock.appendChild(right);
  doc.body.appendChild(metaBlock);

  doc.body.appendChild(doc.importNode(body, true));

  const footer = block(doc, 'div', 'footer');
  footer.textContent =
    'Generated by SyncSenta AI Educational OS - Supporting the Kenyan Curriculum';
  doc.body.appendChild(footer);
}
